class Mapping:
    mapping = {
        "abt":{"text":""
        },
        "cmnd": {
            "Họ và tên": "name",
            "Họ tên": "name",
            "Họ và tên / Full name": "name",
            "id": "id_card",
            "Số / No": "id_card",
            "Ngày, tháng, năm sinh": "dob",
            "Sinh ngày": "dob",
            "Ngày sinh / Date of birth": "dob",
            "Giới tính": "sex",
            "Giới tính / Sex": "sex",
            "Quốc tịch": "nationality",
            "Quốc tịch / Nationality": "nationality",
            "Quê quán": "poo",
            "Quê quán / Place of origin": "poo",
            "Nguyên quán": "poo",
            "Nơi thường trú": "por",
            "Nơi thường trú / Place of residence": "por",
            "Nơi ĐKHK thường trú": "por",
            "Có giá trị đến": "doe",
            "Có giá trị đến / Date of expiry": "doe",
            "Đặc điểm nhận dạng": "pi",
            "Dấu vết riêng và dị hình": "pi",
            "Đặc điểm nhận dạng / Personal identification": "pi",
            "Ngày làm CMND": "dop",
            "Ngày, tháng, năm / Date, month, year": "dop",
            "Giám đốc CA": "poi",
        },
        "cccc": {
            "Họ và tên": "name",
            "Họ tên": "name",
            "Họ và tên / Full name": "name",
            "id": "id_card",
            "Số / No": "id_card",
            "Ngày, tháng, năm sinh": "dob",
            "Sinh ngày": "dob",
            "Ngày sinh / Date of birth": "dob",
            "Giới tính": "sex",
            "Giới tính / Sex": "sex",
            "Quốc tịch": "nationality",
            "Quốc tịch / Nationality": "nationality",
            "Quê quán": "poo",
            "Quê quán / Place of origin": "poo",
            "Nguyên quán": "poo",
            "Nơi thường trú": "por",
            "Nơi thường trú / Place of residence": "por",
            "Nơi ĐKHK thường trú": "por",
            "Có giá trị đến": "doe",
            "Có giá trị đến / Date of expiry": "doe",
            "Đặc điểm nhận dạng": "pi",
            "Dấu vết riêng và dị hình": "pi",
            "Đặc điểm nhận dạng / Personal identification": "pi",
            "Ngày làm CMND": "dop",
            "Ngày, tháng, năm / Date, month, year": "dop",
            "Giám đốc CA": "poi",
        },
        "cccd": {
            "Họ và tên": "name",
            "Họ tên": "name",
            "Họ và tên / Full name": "name",
            "id": "id_card",
            "Số / No": "id_card",
            "Ngày, tháng, năm sinh": "dob",
            "Sinh ngày": "dob",
            "Ngày sinh / Date of birth": "dob",
            "Giới tính": "sex",
            "Giới tính / Sex": "sex",
            "Quốc tịch": "nationality",
            "Quốc tịch / Nationality": "nationality",
            "Quê quán": "poo",
            "Quê quán / Place of origin": "poo",
            "Nguyên quán": "poo",
            "Nơi thường trú": "por",
            "Nơi thường trú / Place of residence": "por",
            "Nơi ĐKHK thường trú": "por",
            "Có giá trị đến": "doe",
            "Có giá trị đến / Date of expiry": "doe",
            "Đặc điểm nhận dạng": "pi",
            "Dấu vết riêng và dị hình": "pi",
            "Đặc điểm nhận dạng / Personal identification": "pi",
            "Ngày làm CMND": "dop",
            "Ngày, tháng, năm / Date, month, year": "dop",
            "Giám đốc CA": "poi",
        },
        "ttk": {
            "SỐ SERI": "seri_number",
            "SỐ CIF": "CIF",
            "CHỦ SỞ HỮU": "name",
            "PHÁP LÝ KHÁCH HÀNG": "id_def",
            "NGÀY CẤP": "datetime_id",
            "NƠI CẤP": "addr_id",
            "SẢN PHẨM": "product_number",
            "NGÀY GỬI TIỀN": "period",
            "NGÀY ĐẾN HẠN": "date_ex",
            "SỐ TK": "TKFD",
        },
        "hc": {
            "Họ và tên / Full name": "name",
            "Số hộ chiếu / Passport N": "passport_id",
            "Số GCMND / ID card N": "id_card",
            "Ngày sinh / Date of birth": "dob",
            "Giới tính / Sex": "sex",
            "Loại / Type": "type",
            "Mã số / Code": "code",
            "Quốc tịch / Nationality": "nationality",
            "Ngày cấp / Date of issue": "dop",
            "Có giá trị đến / Date of expiry": "doe",
            "Nơi cấp / Place of issue": "poi",
            "Nơi sinh / Place of birth": "dob",
        },
        "dkkd": {
            "Tên công ty viết bằng tiếng Việt": "name_VN",
            "Tên công ty viết bằng tiếng nước ngoài": "name_other",
            "Tên công ty viết tắt": "name_code",
            "Địa chỉ trụ sở chính": "addr",
            "Điện thoại": "phone_number",
            "Email": "email",
            "Website": "website",
            "Vốn điều lệ": "equity",
            "Mã số doanh nghiệp": "company_code",
            "Đăng ký lần đầu": "dof",
            "Họ và tên": "incharge",
            "Giới tính": "sex",
            "Chức danh": "title",
            "Sinh ngày": "dob",
            "Loại giấy tờ pháp lý của cá nhân": "id_def",
            "Ngày cấp": "Ngày cấp",
            "Địa chỉ thường trú": "incharge_addr",
            "Địa chỉ liên lạc": "incharge_addr_now",
        },
        "sohong": {
            "id": "id_def",
            "tên ông": "name_mr",
            "Năm sinh ông": "dob_mr",
            "id ông": "id_card_mr",
            "Địa chỉ ông": "addr_mr",
            "tên bà": "name_mrs",
            "Năm sinh bà": "dob_mrs",
            "id bà": "id_card_mrs",
            "Địa chỉ bà": "addr_mrs",
            "Thửa đất số": "id_place",
            "Tờ bản đồ số": "id_map",
            "Địa chỉ": "addr_def",
            "Diện tích": "vacant",
            "Mục đích sử dụng": "objective",
            "Thời hạn sử dụng": "datetime",
            "Nguồn gốc sử dụng": "source",
            "Diện tích sàn": "vacant_house_size",
            "Cấp (Hạng)": "level_house",
            "Thời hạn sở hữu": "datetime_house",
            "Ghi chú": "note",
            "Địa điểm": "place_def",
            "Ngày, tháng, năm": "datetime_place",
            "Nội dung thay đổi và cơ sở pháp lý": "change_content",
        },
    }
    template = {
        "abt":{"text":""

        },
        "cmnd": {
            "name": "Ho va ten",
            "id_card": "So cmt/cccd",
            "dob": "ngay thang nam sinh",
            "poo": "que quan",
            "por": "noi thuong tru",
            "pi": "dac diem nhan dang",
            "dop": "ngay cap cmt/cccd",
            
        },
        "cccc": {
            "name": "Ho va ten",
            "id_card": "So cmt/cccd",
            "dob": "ngay thang nam sinh",
            "sex": "gioi tinh",
            "nationality": "quoc tich",
            "poo": "que quan",
            "por": "noi thuong tru",
            "doe": "ngay het han cmt/cccd",
            "pi": "dac diem nhan dang",
            "dop": "ngay cap cmt/cccd",
           
        },
         "cccd": {
            "name": "Ho va ten",
            "id_card": "So cmt/cccd",
            "dob": "ngay thang nam sinh",
            "sex": "gioi tinh",
            "nationality": "quoc tich",
            "poo": "que quan",
            "por": "noi thuong tru",
            "doe": "ngay het han cmt/cccd",
            "pi": "dac diem nhan dang",
            "dop": "ngay cap cmt/cccd",
           
        },
        "ttk": {
            "CIF": "Số CIF",
            "name": "họ và tên",
            "dob": "Ngày sinh",
            "id_def": "số chứng minh thư",
            "datetime_id": "ngày cấp",
            "addr_id": "địa chỉ cấp",
            "seri_number": "Số seri của sổ",
            "product_number": "tên sản phẩm tích kiệm",
            "TKFD": "Số TFKD",
            "period": "01/01/1970",
            "date_ex": "01/01/1970",
            "price": "0",
        },
        "hc": {
            "name": "Ho va ten",
            "id_card": "So id",
            "passport_id": "So ho chieu",
            "dob": "ngay thang nam sinh",
            "sex": "gioi tinh",
            "nationality": "quoc tich",
            "pob": "noi sinh",
            "doe": "ngay het han cmt/cccd",
            "dop": "ngay cap ho chieu",
            "poi": "noi cap ho chieu",
            "type": "loai ho chieu",
            "code": "ma so",
        },
        "sohong": {
            "name_mr": "tên ông",
            "dob_mr": "ngày sinh ông",
            "id_card_mr": "cmnd của ông",
            "addr_mr": "địa chỉ thường trú ông",
            "name_mrs": "tên bà",
            "dob_mrs": "ngày sinh ông",
            "id_card_mrs": "cmnd của ông",
            "addr_mrs": "địa chỉ thường trú ông",
            "id_def": "số sổ hồng - mặt 1",
            "id_place": "số thửa đất",
            "id_map": "tờ bản đồ số",
            "addr_def": "địa chỉ đất",
            "vacant": "diện tích đất",
            "type": "hình thức sử dụng",
            "objective": "mục đích sử dụng đất",
            "datetime": "thời gian sử dụng đất",
            "source": "nguồn gốc sử dụng đất",
            "note": "",
            "house_addr": "địa chỉ nơi ở",
            "vacant_house_building": "diện tích xây dựng",
            "vacant_house_size": "diện tích sàn",
            "type_house": "kết cấu nhà",
            "level_house": " cấp nhà",
            "building_done": " năm hoàn thành xây dựng",
            "datetime_house": "thời gian sở hữu",
            "place_def": "nơi đăng ký sổ hồng",
            "datetime_place": "ngày tháng đăng ký sổ hồng",
            "signature": "nơi ký cấp sổ hồng",
            "code_def": "số sổ cấp GCN",
        },
        "dkkd": {
            "name_VN": "tên công ty",
            "name_other": "tên công ty nước ngoài",
            "name_code": "tên viết tắt",
            "addr": "địa chỉ trụ sở chính",
            "phone_number": "sdt liên hệ",
            "email": "",
            "website": "",
            "equity": "vốn điều lệ",
            "incharge": "người đại diện công ty",
            "company_code": "mã số doanh nghiệp",
            "dof": "đăng ký lần đầu thời điểm nào",
            "number_change": "Số lần thay đổi",
            "change_datetime": "ngày tháng thay đổi",
            "sex": "gioi tinh",
            "title": "chức danh",
            "dob": "sinh ngày",
            "region": "quốc tịch",
            "id_def": "loại giấy tờ chứng thực cá nhân",
            "doi": "ngày cấp giấy tờ chứng thực",
            "incharge_addr": "nơi đăng ký hộ khẩu thường trú",
            "incharge_addr_now": "chỗ ở hiện tại",
        },
    }
